CREATE TABLE DUOC.BACSI
(
MABS CHAR(5) NOT NULL,
HOTEN VARCHAR(100),
CONSTRAINT PK_BACSI PRIMARY KEY (MABS)
);

CREATE TABLE DUOC.KHOAPHONG 
(
	MAKP CHAR(3) NOT NULL, 
	TENKP VARCHAR(50), 
	KYHIEU VARCHAR(10), 
	SOGIUONGKH SMALLINT, 
	SOGIUONGTK SMALLINT, 
	LOAI SMALLINT, 
	HIEULUC SMALLINT, 
	MASPSD CHAR(15), 
	MAKPMEDI CHAR(2), 
	STT SMALLINT DEFAULT 0,
	CONSTRAINT PK_KHOAPHONG PRIMARY KEY(MAKP)
);

CREATE TABLE DUOC.GIABAN
(
STT SMALLINT NOT NULL,
GIATHAP DOUBLE,
GIACAO DOUBLE,
TYLE SMALLINT,
CONSTRAINT PK_GIABAN PRIMARY KEY (STT)
);


ALTER TABLE DUOC.PHIEUXUAT ADD COLUMN MABS CHAR(5);
ALTER TABLE DUOC.PHIEUXUAT ADD COLUMN CHANDOAN VARCHAR(200);
ALTER TABLE DUOC.PHIEUXUAT ADD CONSTRAINT FK_BACSI FOREIGN KEY (MABS) REFERENCES DUOC.BACSI(MABS);
ALTER TABLE DUOC.PHIEUXUAT ADD COLUMN MAKP CHAR(3);
ALTER TABLE DUOC.PHIEUXUAT ADD CONSTRAINT FK_KHOAPHONG FOREIGN KEY (MAKP) REFERENCES DUOC.KHOAPHONG(MAKP);
ALTER TABLE DUOC.PHIEUXUAT ADD COLUMN TENDANGNHAP CHAR(50); 
ALTER TABLE DUOC.PHIEUXUAT ADD CONSTRAINT FK_NGUOIDUNG FOREIGN KEY (TENDANGNHAP) REFERENCES DUOC.NGUOIDUNG(TENDANGNHAP);

ALTER TABLE DUOC.CHITIETXUAT ADD COLUMN CACHDUNG VARCHAR(200);

ALTER TABLE DUOC.KHACHHANG ADD COLUMN NAMSINH SMALLINT;
ALTER TABLE DUOC.KHACHHANG ADD COLUMN GIOITINH SMALLINT;

