CREATE OR REPLACE VIEW DUOC.VIEWSANPHAM AS 
SELECT SP.MASP, 
	SP.DONVIID, 
	SP.NHOMSPID, 
	SP.TENSP, 
	SP.HOATCHAT, 
	SP.HANGSX, 
	SP.NUOCSX, 
	SP.TRONGNUOC,
	NH.TENNHOMSP,
	NH.LOAISPID,
	LO.TENLOAISP,
	DV.TENDONVI,
	SP.HIEULUC
FROM DUOC.SANPHAM SP 
	JOIN DUOC.NHOMSP NH ON SP.NHOMSPID = NH.NHOMSPID 
	JOIN DUOC.LOAISP LO ON NH.LOAISPID = LO.LOAISPID
	JOIN DUOC.DONVI DV ON SP.DONVIID = DV.DONVIID;
